define([
	"./mini",
	"troopjs-browser/store/adapter/local",
	"troopjs-browser/store/adapter/session",
	"troopjs-utils/filter",
	"troopjs-utils/getargs",
	"troopjs-utils/merge",
	"troopjs-utils/tr",
	"troopjs-utils/unique",
	"troopjs-jquery/action",
	"troopjs-jquery/resize"
]);
