define([
	"troopjs-core/logger/console",
	"troopjs-core/logger/pubsub",
	"troopjs-core/logger/service",
	"troopjs-net/ajax/service",
	"troopjs-browser/application/widget",
	"troopjs-browser/mvc/controller/widget",
	"troopjs-browser/mvc/route/widget"
]);
