define([
	"troopjs-core/net/uri",
	"troopjs-core/logger/console",
	"troopjs-core/logger/pubsub",
	"troopjs-core/logger/service",
	"troopjs-browser/ajax/service",
	"troopjs-browser/application/widget",
	"troopjs-browser/hash/widget",
	"troopjs-browser/mvc/route/widget",
	"troopjs-browser/mvc/controller/widget"
]);
